{ "type": "Feature", "properties": { "id": 162, "nombre": "General Pueyrredón" },      "geometry": { "type": "Point", "coordinates": [-57.743144039076,-37.9656760017008] } },
{ "type": "Feature", "properties": { "id": 128, "nombre": "La Plata" },                "geometry": { "type": "Point", "coordinates": [-58.0180274991075,-35.0034938071388] } },
{ "type": "Feature", "properties": { "id": 933, "nombre": "La Matanza" },              "geometry": { "type": "Point", "coordinates": [-58.625448693896,-34.7701647288425] } },
{ "type": "Feature", "properties": { "id": 407, "nombre": "Esteban Echeverria" },      "geometry": { "type": "Point", "coordinates": [-58.476969025414,-34.8312099703342] } },
{ "type": "Feature", "properties": { "id": 939, "nombre": "Moreno" },                  "geometry": { "type": "Point", "coordinates": [-58.8109232680035,-34.610617117824] } },
{ "type": "Feature", "properties": { "id": 955, "nombre": "Almirante Brown" },         "geometry": { "type": "Point", "coordinates": [-58.3673978494737,-34.8355700988623] } },
{ "type": "Feature", "properties": { "id": 106, "nombre": "Escobar" },                 "geometry": { "type": "Point", "coordinates": [-58.7711281467366,-34.328718150088] } },
{ "type": "Feature", "properties": { "id": 930, "nombre": "Malvinas Argentinas" },     "geometry": { "type": "Point", "coordinates": [-58.7121329971982,-34.4873038284663] } },
{ "type": "Feature", "properties": { "id": 943, "nombre": "Quilmes" },                 "geometry": { "type": "Point", "coordinates": [-58.2768874201614,-34.7350141996909] } },
{ "type": "Feature", "properties": { "id": 157, "nombre": "Pergamino" },               "geometry": { "type": "Point", "coordinates": [-60.5450748689576,-33.8358155353661] } },
{ "type": "Feature", "properties": { "id": 927, "nombre": "Lomas de Zamora" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 926, "nombre": "Ituzaingó" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 924, "nombre": "Morón" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 74,  "nombre": "Azul" },                    "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 947, "nombre": "General San Martín" },      "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 159, "nombre": "Pilar" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 95,  "nombre": "Chacabuco" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 130, "nombre": "Lanús" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 75,  "nombre": "Bahía Blanca" },            "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 69,  "nombre": "General Alvarado" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 151, "nombre": "Necochea" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 126, "nombre": "Junín" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 948, "nombre": "Merlo" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 84,  "nombre": "Bragado" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 72,  "nombre": "Avellaneda" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 952, "nombre": "Vicente López" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 185, "nombre": "Tandil" },                  "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 64,  "nombre": "Nueve de Julio" },          "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 164, "nombre": "Ramallo" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 951, "nombre": "San Nicolás" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 183, "nombre": "San Vicente" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 957, "nombre": "Cañuelas" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 155, "nombre": "Pehuajó" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 938, "nombre": "San Miguel" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 954, "nombre": "General Rodríguez" },       "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 197, "nombre": "Zárate" },                  "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 412, "nombre": "Villa Gesell" },            "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 949, "nombre": "Florencio Varela" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 86,  "nombre": "Campana" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 139, "nombre": "Luján" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 923, "nombre": "Hurlingham" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 82,  "nombre": "Berisso" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 158, "nombre": "Pila" },                    "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 929, "nombre": "Ezeiza" },                  "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 193, "nombre": "General Viamonte" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 132, "nombre": "Las Flores" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 101, "nombre": "Coronel Pringles" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 135, "nombre": "Lincoln" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 91,  "nombre": "Carmen de Areco" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 184, "nombre": "Suipacha" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 195, "nombre": "Villarino" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 114, "nombre": "General Lavalle" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 137, "nombre": "Lobos" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 141, "nombre": "Maipú" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 133, "nombre": "General Las Heras" },       "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 932, "nombre": "Tres de Febrero" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 88,  "nombre": "Capitán Sarmiento" },       "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 80,  "nombre": "Benito Juárez" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 940, "nombre": "Tigre" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 65,  "nombre": "Adolfo Alsina" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 190, "nombre": "Trenque Lauquen" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 73,  "nombre": "Ayacucho" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 67,  "nombre": "Alberti" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 108, "nombre": "Exaltación de la Cruz" },   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 76,  "nombre": "Balcarce" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 77,  "nombre": "Baradero" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 85,  "nombre": "Coronel Brandsen" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 78,  "nombre": "Arrecifes" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 83,  "nombre": "Bolívar" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 103, "nombre": "Daireaux" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 90,  "nombre": "Carlos Tejedor" },          "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 177, "nombre": "San Isidro" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 94,  "nombre": "Castelli" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 89,  "nombre": "Carlos Casares" },          "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 113, "nombre": "General Guido" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 98,  "nombre": "Colón" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 96,  "nombre": "Chascomús" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 100, "nombre": "Coronel Dorrego" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 112, "nombre": "General Belgrano" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 104, "nombre": "Dolores" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 97,  "nombre": "Chivilcoy" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 111, "nombre": "General Arenales" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 131, "nombre": "Laprida" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 117, "nombre": "General Pinto" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 70,  "nombre": "General Alvear" },          "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 129, "nombre": "General La Madrid" },       "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 115, "nombre": "General Madariaga" },       "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 116, "nombre": "General Paz" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 66,  "nombre": "Adolfo Gonzales Chaves" },  "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 121, "nombre": "Guaminí" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 134, "nombre": "Leandro N. Alem" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 140, "nombre": "Magdalena" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 136, "nombre": "Lobería" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 102, "nombre": "Coronel Suárez" },          "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 411, "nombre": "La Costa" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 144, "nombre": "Marcos Paz" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 120, "nombre": "General Villegas" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 410, "nombre": "Pinamar" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 154, "nombre": "Olavarría" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 92,  "nombre": "Patagones" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 950, "nombre": "Berazategui" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 105, "nombre": "Ensenada" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 172, "nombre": "Salto" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 925, "nombre": "San Fernando" },            "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 182, "nombre": "San Pedro" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 953, "nombre": "Presidente Perón" },        "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 150, "nombre": "Navarro" },                 "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 143, "nombre": "Mar Chiquita" },            "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 180, "nombre": "Monte" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 166, "nombre": "Rivadavia" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 167, "nombre": "Rojas" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 161, "nombre": "Puan" },                    "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 165, "nombre": "Rauch" },                   "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 168, "nombre": "Roque Pérez" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 170, "nombre": "Saladillo" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 145, "nombre": "Mercedes" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 174, "nombre": "San Antonio de Areco" },    "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 169, "nombre": "Saavedra" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 173, "nombre": "San Andrés de Giles" },     "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 186, "nombre": "Tapalqué" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 175, "nombre": "San Cayetano" },            "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 188, "nombre": "Tordillo" },                "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 196, "nombre": "Hipólito Yrigoyen" },       "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 63,  "nombre": "Veinticinco de Mayo" },     "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 77,  "nombre": "Islas Baradero" },          "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 197, "nombre": "Islas de Zárate" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 925, "nombre": "Islas San Fernando" },      "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 147, "nombre": "Monte Hermoso" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 164, "nombre": "Islas Ramallo" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 182, "nombre": "Islas San Pedro" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 409, "nombre": "Punta Indio" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 71,  "nombre": "Florentino Ameghino" },     "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 189, "nombre": "Tornquist" },               "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 956, "nombre": "Lezama" },                  "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 922, "nombre": "Tres Lomas" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 191, "nombre": "Tres Arroyos" },            "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 934, "nombre": "José C. Paz" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 86,  "nombre": "Islas Campana" },           "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 99,  "nombre": "Coronel Rosales" },         "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 940, "nombre": "Islas Tigre" },             "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 951, "nombre": "Islas de San Nicolas" },    "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 156, "nombre": "Pellegrini" },              "geometry": { "type": "Point", "coordinates": [] } },
{ "type": "Feature", "properties": { "id": 171, "nombre": "Salliqueló" },              "geometry": { "type": "Point", "coordinates": [] } },
